name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          plugin: asdf-yamlscript
          version: latest
          gitref: main
          command: ys --version
